### PR TITLE
Make Croquet Model reactive + Leave session automatically

### PR DESCRIPTION
**Pull request by afonsocrg**

### CODE REVIEW

**Comment by yoshikiohshima** [comment]
How do I test the bindings with examples?

**Comment by afonsocrg** [comment]
@yoshikiohshima to test locally we have been using example repositories (e.g. mondrian), and linking the react bindings using the command `npm link <path-to-bindings>`. I believe you should remove the `node_modules` first, and then remove the dependency from the `package.json` file.

**Comment by yoshikiohshima** [comment]
Running `npm install` in the bindings with this pull request seems to have a problem of the output index.d.ts specified as source:
```
error TS5055: Cannot write file '/Users/ohshima/src/croquet/croquet-react/bindings/dist/index.d.ts' because it would overwrite input file.
```

**Comment by afonsocrg** [comment]
@yoshikiohshima Since that error was already fixed in a more 'advanced' branch, and it did not contain too many new changes, I merged them into this one, so now you should have everything ready.

If you test the Counter and MusicBox repos, make sure that you're in the branch `hookified`, since they have the changes required to work with this version.

**Pull request merged**
